name: Linux Day Barletta 2016
description: "Sabato 22 ottobre: appuntamento con Tux. Puglia Software Open Source organizza il Linux Day 2016 a Barletta!"
alt_name: Linux Day 2016 - Barletta
event_date: 22 ottobre
event_name: Linux Day 2016
event_name_short: LD'16
url: http://linuxdaybarletta.it
hashtag: LinuxDay2016
tweet: Linux Day 2016 a Barletta!
twitter: LDBarletta
facebook: https://www.facebook.com/PugliaSOS
google_plus: //plus.google.com/118028692961657819578
markdown: redcarpet
highlighter: rouge
last_update_text: "Ultimo aggiornamento: "
jquery: 1.11.1
registration: linuxday-barletta-2016-partecipazione.html
contacts: linuxday-barletta-2016-contatti.html
where: linuxday-barletta-2016-dove-saremo.html
banner_square_small: http://www.linuxday.it/sites/default/files/banners/banner_180x150.png
banner_square_big: http://www.linuxday.it/sites/default/files/banners/banner_300x250.png
banner_horizontal: http://www.linuxday.it/sites/default/files/banners/banner_468x60.png
banner_vertical: http://www.linuxday.it/sites/default/files/banners/banner_120x600.png
encoded_email: "&#109;&#097;&#105;&#108;377867bca0ab759b28b215d31e10ad8b&#116;&#111;&#058;&#105;&#110;&#102;&#111;&#064;&#108;&#105;&#110;&#117;&#120;&#100;&#097;&#121;377867bca0ab759b28b215d31e10ad8b&#098;&#097;&#114;&#108;&#101;&#116;&#116;&#097;&#046;&#105;&#116;"
navbar_right_elem: true
