name: Linux Day Barletta 2017
description: "Sabato 28 ottobre: appuntamento con Tux. Puglia Software Open Source organizza il Linux Day 2017 a Barletta!"
alt_name: Linux Day 2017 - Barletta
event_date: 28 ottobre
event_schema_date: 2017-10-28
event_edition: 2017
event_name: Linux Day 2017
event_name_short: LD'17
event_local_name: Linux Day Barletta 2017
event_short_local_name: LD17 Barletta
event_location: Istituto Tecnico Tecnologico Enrico Fermi
event_short_location: ITT Enrico Fermi
event_location_address: via Madonna della Croce 265
url: http://linuxdaybarletta.it
hashtag: LinuxDay2017
tweet: Linux Day 2017 a Barletta!
twitter: LDBarletta
facebook: https://www.facebook.com/PugliaSOS
google_plus: //plus.google.com/118028692961657819578
markdown: redcarpet
highlighter: rouge
last_update_text: "Ultimo aggiornamento: "
jquery: 1.11.1
registration: linuxday-barletta-2017-partecipazione.html
contacts: linuxday-barletta-2017-contatti.html
where: linuxday-barletta-2017-dove-saremo.html
banner_square_small: http://www.linuxday.it/sites/default/files/banners/banner_180x150.png
banner_square_big: http://www.linuxday.it/sites/default/files/banners/banner_300x250.png
banner_horizontal: http://www.linuxday.it/sites/default/files/banners/banner_468x60.png
banner_vertical: http://www.linuxday.it/sites/default/files/banners/banner_120x600.png
encoded_email: "&#109;&#097;&#105;&#108;377867bca0ab759b28b215d31e10ad8b&#116;&#111;&#058;&#105;&#110;&#102;&#111;&#064;&#108;&#105;&#110;&#117;&#120;&#100;&#097;&#121;377867bca0ab759b28b215d31e10ad8b&#098;&#097;&#114;&#108;&#101;&#116;&#116;&#097;&#046;&#105;&#116;"
navbar_right_elem: true
piwik_analytics_url: http://nicola.link/ldb-analytics/
timezone: Europe/Rome
